---
name: PR labels

on: # zizmor: ignore[dangerous-triggers]
  pull_request_target:
    types:
      - opened
      - labeled
      - unlabeled
      - synchronize

permissions:
  pull-requests: read

jobs:
  verify:
    name: Verify
    runs-on: ubuntu-latest
    steps:
      - name: 🏷 Verify PR has a valid label
        # zizmor: ignore[unpinned-uses]
        uses: jesusvasquez333/verify-pr-label-action@657d111bbbe13e22bbd55870f1813c699bde1401 # v1.4.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          valid-labels: >-
            breaking-change, bugfix, dependencies, documentation,
            enhancement, performance, refactor
          pull-request-number: ${{ github.event.pull_request.number }}
          disable-reviews: true
